packages:
  - internal/*
  - packages/*
  - apps/*
  - scripts/*
  - docs
  - playground

catalog:
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.7
  '@changesets/git': ^3.0.4
  '@clack/prompts': ^0.10.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@ctrl/tinycolor': ^4.2.0
  '@eslint/js': ^9.37.0
  '@iconify/vue': ^5.0.0
  '@intlify/core-base': ^11.1.12
  '@intlify/unplugin-vue-i18n': ^6.0.8
  '@manypkg/get-packages': ^3.1.0
  '@nolebase/vitepress-plugin-git-changelog': ^2.18.2
  '@playwright/test': ^1.56.0
  '@tailwindcss/typography': ^0.5.19
  '@tanstack/vue-query': ^5.90.2
  '@tanstack/vue-store': ^0.7.7
  '@types/archiver': ^6.0.3
  '@types/eslint': ^9.6.1
  '@types/html-minifier-terser': ^7.0.2
  '@types/json-bigint': ^1.0.4
  '@types/node': ^22.18.9
  '@types/nprogress': ^0.2.3
  '@types/qrcode': ^1.5.5
  '@types/qs': ^6.14.0
  '@typescript-eslint/eslint-plugin': ^8.46.0
  '@typescript-eslint/parser': ^8.46.0
  '@vee-validate/zod': ^4.15.1
  '@vite-pwa/vitepress': ^1.0.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vue/reactivity': ^3.5.22
  '@vue/shared': ^3.5.22
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.9.0
  '@vueuse/integrations': ^13.9.0
  '@vueuse/motion': ^3.0.3
  ant-design-vue: ^4.2.6
  archiver: ^7.0.1
  autoprefixer: ^10.4.21
  axios: ^1.12.2
  cac: ^6.7.14
  chalk: ^5.6.2
  cheerio: ^1.1.2
  circular-dependency-scanner: ^2.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitlint-plugin-function-rules: ^4.1.0
  consola: ^3.4.2
  cross-env: ^7.0.3
  cspell: ^8.19.4
  cssnano: ^7.1.1
  cz-git: ^1.12.0
  czg: ^1.12.0
  dayjs: ^1.11.18
  defu: ^6.1.4
  depcheck: ^1.4.7
  dotenv: ^16.6.1
  element-plus: ^2.11.4
  eslint: ^9.37.0
  eslint-config-turbo: ^2.5.8
  eslint-plugin-command: ^3.3.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^50.8.0
  eslint-plugin-jsonc: ^2.21.0
  eslint-plugin-n: ^17.23.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.2.0
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.5.0
  execa: ^9.6.0
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^16.4.0
  happy-dom: ^17.6.3
  html-minifier-terser: ^7.2.0
  json-bigint: ^1.0.0
  jsonc-eslint-parser: ^2.4.1
  lefthook: ^1.13.6
  lucide-vue-next: ^0.507.0
  medium-zoom: ^1.1.0
  naive-ui: ^2.43.1
  nitropack: ^2.12.7
  nprogress: ^0.2.0
  ora: ^8.2.0
  pinia: ^3.0.3
  pkg-types: ^2.3.0
  playwright: ^1.56.0
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  publint: ^0.3.14
  qrcode: ^1.5.4
  qs: ^6.14.0
  radix-vue: ^1.9.17
  resolve.exports: ^2.0.3
  rimraf: ^6.0.1
  rollup: ^4.52.4
  rollup-plugin-visualizer: ^5.14.0
  sass: ^1.93.2
  secure-ls: ^2.0.0
  tailwind-merge: ^2.6.0
  tailwindcss: ^4.1.14
  theme-colors: ^0.1.0
  tippy.js: ^6.3.7
  turbo: ^2.5.8
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unplugin-element-plus: ^0.10.0
  vee-validate: ^4.15.1
  vite: ^7.1.9
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^1.0.3
  vite-plugin-vue-devtools: ^7.7.7
  vitepress: ^1.6.4
  vitepress-plugin-group-icons: ^1.6.3
  vitest: ^3.2.4
  vue: ^3.5.22
  vue-eslint-parser: ^10.2.0
  vue-i18n: ^11.1.12
  vue-json-viewer: ^3.0.4
  vue-router: ^4.5.1
  vue-tippy: ^6.7.1
  vue-tsc: ^3.1.1
  vxe-pc-ui: ^4.9.42
  vxe-table: ^4.16.21
  watermark-js-plus: ^1.6.3
  zod: ^3.25.76
  zod-defaults: ^0.1.3

peerDependencyRules:
  allowedVersions:
    eslint: '*'

overrides:
  esbuild: 0.25.10
  vue: ^3.5.22

neverBuiltDependencies: [canvas, node-gyp]
